steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - positivity-bot
  - --region=europe-west2
  - --source=.
  - --trigger-topic=trigger-positivity-message
  - --runtime=nodejs20
  - --entry-point=pingDiscord